name: Get secrets from secret manager
on: 
  workflow_dispatch

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
				token_format: 'access token'
        workload_identity_provider: 'projects/103365112501/locations/global/workloadIdentityPools/githubactions/provider/my-provider'
        service_account: 'github-actions@eurus-project-dev.iam.gserviceaccount.com'

    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
       gcloud secrets version access "latest" --secret "my-secret"
